project:
  type: book
  output-dir: docs

book:
  title: "Orchestrating Hi-C analysis with Bioconductor"
  reader-mode: false
  page-footer:
    left: |
      OHCA: Orchestrating Hi-C analysis with Bioconductor was written by 
      Jacques Serizay
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://js2264.github.io/OHCA/
  repo-url: https://github.com/js2264/OHCA/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: "Fundamentals concepts"
      chapters:
        - principles.qmd
        - data-representation.qmd
        - parsing.qmd
        - visualization.qmd
    - part: "In-depth Hi-C analysis"
      chapters:
        - matrix-centric.qmd
        - interactions-centric.qmd
        - topological-features.qmd
    - part: "Advanced Hi-C topics"
      chapters:
        - workflow-yeast.qmd
        - workflow-chicken.qmd
        - interoperability.qmd
        - disseminating.qmd

format:
  html:
    default-image-extension: pdf
    theme:
      - yeti
      - OHCA.scss
    code-link: true
    author-meta: "Jacques Serizay"
    callout-appearance: simple
    highlight-style: atom-one-dark.theme
  pdf:
    documentclass: scrbook
    papersize: a4
    toc: true
    toc-title: Contents
    number-sections: true
    colorlinks: true
    default-image-extension: pdf
    theme:
      - yeti
      - OHCA.scss
    code-link: true
    author-meta: "Jacques Serizay"
    callout-appearance: simple
    highlight-style: atom-one-dark.theme

editor: visual
