project:
  type: book
  output-dir: docs

book:
  title: "OHCA: Orchestrating Hi-C analysis with Bioconductor"
  reader-mode: false
  page-footer:
    left: |
      OHCA: Orchestrating Hi-C analysis with Bioconductor was written by 
      Jacques Serizay
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://github.com/js2264.OHCA/
  repo-url: https://github.com/js2264.OHCA/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: "Fundamentals concepts"
      chapters:
        - principles.qmd
        - data-representation.qmd
        - parsing.qmd
        - visualization.qmd
    - part: "In-depth Hi-C analysis"
      chapters:
        - arithmetics.qmd
        - metrics.qmd
        - topological-features.qmd
    - part: "Advanced Hi-C topics"
      chapters:
        - workflows.qmd
        - interoperability.qmd

format:
  html:
    default-image-extension: pdf
    theme:
      - cosmo
      - OHCA.scss
    code-link: true
    author-meta: "Jacques Serizay"
    callout-appearance: simple

editor: visual
