project:
  type: book
  output-dir: docs

book:
  title: "Orchestrating Hi-C analysis with Bioconductor"
  reader-mode: false
  page-footer:
    left: |
      <i>OHCA: Orchestrating Hi-C analysis with Bioconductor</i> was written by 
      J. Serizay
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://js2264.github.io/OHCA/
  repo-url: https://github.com/js2264/OHCA/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: "Fundamentals concepts"
      chapters:
        - principles.qmd
        - data-representation.qmd
        - parsing.qmd
        - visualization.qmd
    - part: "In-depth Hi-C analysis"
      chapters:
        - matrix-centric.qmd
        - interactions-centric.qmd
        - topological-features.qmd
    - part: "Advanced Hi-C topics"
      chapters:
        - disseminating.qmd
        - workflow-yeast.qmd
        - workflow-chicken.qmd
        - workflow-centros.qmd
        # - interoperability.qmd

format:
  html:
    default-image-extension: pdf
    theme:
      - yeti
      - OHCA.scss
    code-link: true
    author-meta: "Jacques Serizay"
    highlight-style: atom-one-dark.theme
    citations-hover: true
    toc: true
    toc-float: 
      collapsed: false
    toc-depth: 3
    website: 
      sidebar: 
        # style: "docked"
        search: true
        collapse-level: 5
  pdf:
    default-image-extension: pdf
    theme:
      - yeti
      - OHCA.scss
    code-link: true
    author-meta: "Jacques Serizay"
    documentclass: scrbook
    papersize: a4
    toc: true
    toc-title: Contents
    number-sections: true
    colorlinks: true

editor: visual
